config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    resource :profile, only: [:edit, :show, :update, :index]
  end

  resources :stories, only: [:create, :new, :show, :index, :edit, :update, :destroy] do
    resources :storyupdates, only: [:new, :create, :show]
  end

  # You can have the root of your site routed with "root"
  root to: 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/storyupdate.rb
class Storyupdate < ActiveRecord::Base
  belongs_to :user
  belongs_to :story
  validates :title, presence: true,
                    length: { minimum: 5, maximum: 140 }
  validates :text, presence: true,
                    length: { minimum: 5, maximum: 140 }
end

app/controllers/storyupdates_controller.rb
class StoryupdatesController < ApplicationController

  before_action :get_story, only: [:new, :show, :edit, :create, :update, :destroy]
  # load_and_authorize_resource

  def index
    @storyupdates = Storyupdate.all
  end

  def new
    @storyupdate = Storyupdate.new
  end

  def create
    @storyupdate = @story.storyupdates.build(storyupdates_params)
    if @storyupdate.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @storyupdate.update(storyupdates_params)
      redirect_to story_path(@storyupdate), notice: 'The story was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @storyupdate.destroy
    redirect_to stories_url, notice: 'The story update was successfully deleted.'
  end

  private

  def get_story
    @story = Story.find(params[:story_id])
  end

  def storyupdates_params
    params.require(:storyupdate).permit(:title, :text)
  end
end

app/helpers/storyupdates_helper.rb
module StoryupdatesHelper
end

app/views/storyupdates/_form.html.erb
<h1><strong>Add to this story!</strong></h1>

<%= form_for @storyupdate, url: story_storyupdates_path(@story.id) do |f| %>

<% if @storyupdate.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@storyupdate.errors.count, "error") %> prohibited
     this story from being saved:</h2>
   <ul>
   <% @storyupdate.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

 <p>
   <%= f.label :title %><br>
   <%= f.text_area :title %>
 </p>

 <p>
   <%= f.label :text %><br>
   <%= f.text_area :text %>
 </p>

 <p>
   <%= f.submit 'Save', class: 'btn btn-default' %>
 </p>
<% end %>

app/views/storyupdates/create.html.erb
<%= form_for :storyupdate, url: storyupdates_path do |f| %>
  <p>
    <%= f.label :Title %><br>
    <%= f.text_field :title%>
  <p>

  <p>
    <%= f.label :Write %><br>
    <%= f.text_area :text %>
  <p>

  <p>
    <%= f.submit %>
  <p>
  <br><br><br>

  <% end %>

app/views/storyupdates/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Back', storyupdate_path %>

app/views/storyupdates/index.html.erb
<h1><strong>Stories</strong></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= link_to story.title, stories_path(story) %></td><br>

        <td><%= link_to 'Edit    ', edit_story_path(story) %></td>

        <td><%= link_to 'Delete', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %> <br>
<%= link_to 'Update this Story', new_story_storyupdate_path %> <br>

app/views/storyupdates/new.html.erb
<%= render 'form' %>

app/views/storyupdates/show.html.erb
<%=render story_path(story)%>